### ISSUE TITLE
recreate_plot should take a figsize argument

### ISSUE THREAD

**Issue by davidmascharka** [rsokl/liveplot#13]
It would be lovely to be able to take a `figsize` in `recreate_plot` so as not to end up with a miniscule plot. When I work out of interactive mode (e.g. when I work in emacs), I'd like to be able to simply construct the plot at the size I want via an interface like:

``` python
plotter, fig, ax  = recreate_plot(train_metrics=train, test_metrics=test, figsize=(8, 12))
```

rather than:

``` python
plotter, fig, ax = recreate_plot(train_metrics=train, test_metrics=test)
fig.set_size_inches(8, 12)
```

**Comment by rsokl** [comment]
This is already in `LivePlot.__init__`!! I have no idea why I didn't expose this to `recreate_plot`...

Will incorporated soon

**Comment by rsokl** [comment]
`recreate_plot` no longer exists, you can now do:

```python
>>> plotter = LivePlot.from_dict("your_old_plotter.pkl")
>>> plotter.plot()
```

That being said, `figsize` is now a set-able property on `LivePlot`!

1d67215
