### ISSUE TITLE
Plotting in server mode

### ISSUE THREAD

**Issue by rsokl** [rsokl/liveplot#9]
Add ability to serve logged data to a plotter. This would permit people to manage a live plot in a separate and multiple notebooks.

This is an ambitious enhancement that has the potential for a large payoff. I would like to carefully consider the best means for serving/listening to data in a simple but robust way. I'd like to get input from other about how to move forward with this (@davidmascharka , @ptran516 , @arjunmajum)

**Comment by ptran516** [comment]
@rsokl The server could be a simple [Flask](http://flask.pocoo.org/docs/1.0/quickstart/) application which pushes data to clients and modifying plot data via HTTP requests. Were you thinking about having it run at some remote machine with an accessible IP?

**Comment by rsokl** [comment]
This is currently out of scope for this project
